### ISSUE TITLE
type initializer exception on .NET Framework

### ISSUE THREAD

**Issue by ispysoftware** [pixiv/webrtc#2] opened 2020-03-27 09:03 UTC
I'm getting a type initializer exception on 

_pcObserver = new DisposablePeerConnectionObserver(observer);

System.TypeInitializationException: 'The type initializer for 'Pixiv.Webrtc.DisposablePeerConnectionObserver' threw an exception.'

MarshalDirectiveException: Cannot marshal 'parameter #3': Invalid managed/unmanaged type combination (Int32/UInt32 must be paired with I4, U4, or Error).

(Using the windows dll jingle_peerconnection_so.dll)

**Comment by akihikodaki** [comment] 2020-03-27 09:07
Can you tell me what caused the exception? I'd like to hear the reason whether it is misuse or not.

**Comment by ispysoftware** [comment] 2020-03-27 09:08
I'm not sure, i closed the issue because i think it's just not resolving the DLL. I'll re-open it if that's not the problem.

**Comment by akihikodaki** [comment] 2020-03-27 09:13
> I'm not sure, i closed the issue because i think it's just not resolving the DLL. I'll re-open it if that's not the problem.

I do not think so. It should throw `System.DllNotFoundException` in the case. Please tell me if you find something suspicious else. I'll appreciate your report.

**Comment by ispysoftware** [comment] 2020-03-27 09:15
Yeah it's a weird one - if i remove the dll from the folder I get the same error. Maybe it's finding it somewhere else.

**Comment by ispysoftware** [comment] 2020-03-27 09:23
I just changed the name in dll.cs to "dll_that_doesnt_exist" and rebuilt it and got the same error so no idea why it's not throwing a dll not found exception.. will investigate.

**Comment by ispysoftware** [comment] 2020-03-27 10:49
I just started a new project, added the jingle_peerconnection_so.dll to it and added 

var observer = new PeerConnectionObserver();
var _pcObserver = new DisposablePeerConnectionObserver(observer);

to program.cs (with a template PeerConnectionObserver class) and had the same issue - is there an init call I need to do to load the dll?

**Comment by akihikodaki** [comment] 2020-03-27 11:00
> is there an init call I need to do to load the dll?

I don't think so.

I wonder what runtime you use. This library is not tested with .NET Framework nor with .NET Core, only with Mono and Unity. I also primarily use Linux for development. Maybe this library has incompatibility with other environments.

**Comment by ispysoftware** [comment] 2020-03-27 11:14
ah ok, i'm using the .net framework and the net standard framework.

**Comment by ispysoftware** [comment] 2020-03-27 11:53
seems to work with .net core

**Comment by akihikodaki** [comment] 2020-03-27 14:49
It seems time to reopen the issue, limiting the scope to .NET Framework.

**Comment by akihikodaki** [comment] 2020-03-27 14:59
By the way, I believe the cause of the exception is something else DLL resolution. The problem is probably that it fails to marshal a parameter *before* actually resolving and passing it to the underlying C function.

**Comment by ispysoftware** [comment] 2020-04-08 01:24
I'm not sure why but it's started working now on .net - possibly something to do with some updates I made to the marshalling classes. It doesn't like the SysInt pointers. I've replaced them with U4.

**Comment by akihikodaki** [comment] 2020-04-30 15:16
Fixed with commit d5bc1cb2fe235fdbcd1128e94be9fcecaf6b2895.

> I'm not sure why but it's started working now on .net - possibly something to do with some updates I made to the marshalling classes. It doesn't like the SysInt pointers. I've replaced them with U4.

Sorry for a late reply. This comment helped me figure out the cause. Thank you so much.

**Closed as completed by akihikodaki** 2020-04-30 15:16 UTC
Labels: bug, help wanted
